In [20]:
import numpy as np
import pandas as pd
from tqdm import tqdm

In [ ]:
books = pd.read_csv("books_with_categories.csv")

In [2]:
from transformers import pipeline
classifier = pipeline("text-classification",
                      model="j-hartmann/emotion-english-distilroberta-base",
                      top_k = None,
                      device = "mps")
classifier("I love this!")

config.json: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/105 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: j-hartmann/emotion-english-distilroberta-base
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/329M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

[[{'label': 'joy', 'score': 0.9771687984466553},
  {'label': 'surprise', 'score': 0.008528691716492176},
  {'label': 'neutral', 'score': 0.005764603149145842},
  {'label': 'anger', 'score': 0.004419785924255848},
  {'label': 'sadness', 'score': 0.002092392183840275},
  {'label': 'disgust', 'score': 0.0016119939973577857},
  {'label': 'fear', 'score': 0.0004138523945584893}]]

In [5]:
books["description"][0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.'

In [6]:
classifier(books["description"][0])

[[{'label': 'fear', 'score': 0.654842734336853},
  {'label': 'neutral', 'score': 0.1698513776063919},
  {'label': 'sadness', 'score': 0.11640817672014236},
  {'label': 'surprise', 'score': 0.02070058509707451},
  {'label': 'disgust', 'score': 0.019100703299045563},
  {'label': 'joy', 'score': 0.015161193907260895},
  {'label': 'anger', 'score': 0.003935147542506456}]]

In [7]:
classifier(books["description"][0].split("."))

[[{'label': 'surprise', 'score': 0.7296028733253479},
  {'label': 'neutral', 'score': 0.14038559794425964},
  {'label': 'fear', 'score': 0.06816215068101883},
  {'label': 'joy', 'score': 0.047942452132701874},
  {'label': 'anger', 'score': 0.00915634073317051},
  {'label': 'disgust', 'score': 0.0026284719351679087},
  {'label': 'sadness', 'score': 0.0021221598144620657}],
 [{'label': 'neutral', 'score': 0.44937148690223694},
  {'label': 'disgust', 'score': 0.2735908031463623},
  {'label': 'joy', 'score': 0.10908294469118118},
  {'label': 'sadness', 'score': 0.09362732619047165},
  {'label': 'anger', 'score': 0.040478236973285675},
  {'label': 'surprise', 'score': 0.026970215141773224},
  {'label': 'fear', 'score': 0.006879065651446581}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273362755775452},
  {'label': 'disgust', 'score': 0.04342261329293251},
  {'label': 'surprise', 'score': 0.028300536796450615},
  {'label': 'joy', 'score': 0.014211433008313179},
  {'label': 'fear', 'score': 0.014084100723266602},
  {'label': 'anger', 'score': 0.011031871661543846}],
 [{'label': 'fear', 'score': 0.9281686544418335},
  {'label': 'anger', 'score': 0.03219055011868477},
  {'label': 'neutral', 'score': 0.012808628380298615},
  {'label': 'sadness', 'score': 0.008756844326853752},
  {'label': 'surprise', 'score': 0.008597871288657188},
  {'label': 'disgust', 'score': 0.008431774564087391},
  {'label': 'joy', 'score': 0.0010455787414684892}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104169026017189},
  {'label': 'disgust', 'score': 0.006480601150542498},
  {'label': 'fear', 'score': 0.005394008010625839},
  {'label': 'surprise', 'score': 0.0022869438398629427},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338803736492991}],
 [{'label': 'joy', 'score': 0.9327977299690247},
  {'label': 'disgust', 'score': 0.03771739453077316},
  {'label': 'neutral', 'score': 0.015891872346401215},
  {'label': 'sadness', 'score': 0.006444512400776148},
  {'label': 'anger', 'score': 0.005024997051805258},
  {'label': 'surprise', 'score': 0.0015812059864401817},
  {'label': 'fear', 'score': 0.0005423080292530358}],
 [{'label': 'joy', 'score': 0.6528704762458801},
  {'label': 'neutral', 'score': 0.25427481532096863},
  {'label': 'surprise', 'score': 0.06808316707611084},
  {'label': 'sadness', 'score': 0.009909004904329777},
  {'label': 'disgust', 'score': 0.006512203719466925},
  {'label': 'anger', 'score': 0.004821311216801405},
  {'label': 'fear', 'score': 0.0035290189553052187}],
 [{'label': 'neutral', 'score': 0.5494773983955383},
  {'label': 'sadness', 'score': 0.11169008165597916},
  {'label': 'disgust', 'score': 0.10400654375553131},
  {'label': 'surprise', 'score': 0.0787653997540474},
  {'label': 'anger', 'score': 0.06413350999355316},
  {'label': 'fear', 'score': 0.05136271193623543},
  {'label': 'joy', 'score': 0.04056432843208313}]]

In [8]:
sentences = books["description"][0].split(".")
predictions = classifier(sentences)

In [9]:
sentences[0]

'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives'

In [10]:
predictions[0]

[{'label': 'surprise', 'score': 0.7296028733253479},
 {'label': 'neutral', 'score': 0.14038559794425964},
 {'label': 'fear', 'score': 0.06816215068101883},
 {'label': 'joy', 'score': 0.047942452132701874},
 {'label': 'anger', 'score': 0.00915634073317051},
 {'label': 'disgust', 'score': 0.0026284719351679087},
 {'label': 'sadness', 'score': 0.0021221598144620657}]

In [11]:
sentences[3]

' Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist'

In [12]:
predictions[3]

[{'label': 'fear', 'score': 0.9281686544418335},
 {'label': 'anger', 'score': 0.03219055011868477},
 {'label': 'neutral', 'score': 0.012808628380298615},
 {'label': 'sadness', 'score': 0.008756844326853752},
 {'label': 'surprise', 'score': 0.008597871288657188},
 {'label': 'disgust', 'score': 0.008431774564087391},
 {'label': 'joy', 'score': 0.0010455787414684892}]

In [13]:
predictions

[[{'label': 'surprise', 'score': 0.7296028733253479},
  {'label': 'neutral', 'score': 0.14038559794425964},
  {'label': 'fear', 'score': 0.06816215068101883},
  {'label': 'joy', 'score': 0.047942452132701874},
  {'label': 'anger', 'score': 0.00915634073317051},
  {'label': 'disgust', 'score': 0.0026284719351679087},
  {'label': 'sadness', 'score': 0.0021221598144620657}],
 [{'label': 'neutral', 'score': 0.44937148690223694},
  {'label': 'disgust', 'score': 0.2735908031463623},
  {'label': 'joy', 'score': 0.10908294469118118},
  {'label': 'sadness', 'score': 0.09362732619047165},
  {'label': 'anger', 'score': 0.040478236973285675},
  {'label': 'surprise', 'score': 0.026970215141773224},
  {'label': 'fear', 'score': 0.006879065651446581}],
 [{'label': 'neutral', 'score': 0.6462157964706421},
  {'label': 'sadness', 'score': 0.24273362755775452},
  {'label': 'disgust', 'score': 0.04342261329293251},
  {'label': 'surprise', 'score': 0.028300536796450615},
  {'label': 'joy', 'score': 0.014211433008313179},
  {'label': 'fear', 'score': 0.014084100723266602},
  {'label': 'anger', 'score': 0.011031871661543846}],
 [{'label': 'fear', 'score': 0.9281686544418335},
  {'label': 'anger', 'score': 0.03219055011868477},
  {'label': 'neutral', 'score': 0.012808628380298615},
  {'label': 'sadness', 'score': 0.008756844326853752},
  {'label': 'surprise', 'score': 0.008597871288657188},
  {'label': 'disgust', 'score': 0.008431774564087391},
  {'label': 'joy', 'score': 0.0010455787414684892}],
 [{'label': 'sadness', 'score': 0.9671574234962463},
  {'label': 'neutral', 'score': 0.015104169026017189},
  {'label': 'disgust', 'score': 0.006480601150542498},
  {'label': 'fear', 'score': 0.005394008010625839},
  {'label': 'surprise', 'score': 0.0022869438398629427},
  {'label': 'anger', 'score': 0.0018428900511935353},
  {'label': 'joy', 'score': 0.0017338803736492991}],
 [{'label': 'joy', 'score': 0.9327977299690247},
  {'label': 'disgust', 'score': 0.03771739453077316},
  {'label': 'neutral', 'score': 0.015891872346401215},
  {'label': 'sadness', 'score': 0.006444512400776148},
  {'label': 'anger', 'score': 0.005024997051805258},
  {'label': 'surprise', 'score': 0.0015812059864401817},
  {'label': 'fear', 'score': 0.0005423080292530358}],
 [{'label': 'joy', 'score': 0.6528704762458801},
  {'label': 'neutral', 'score': 0.25427481532096863},
  {'label': 'surprise', 'score': 0.06808316707611084},
  {'label': 'sadness', 'score': 0.009909004904329777},
  {'label': 'disgust', 'score': 0.006512203719466925},
  {'label': 'anger', 'score': 0.004821311216801405},
  {'label': 'fear', 'score': 0.0035290189553052187}],
 [{'label': 'neutral', 'score': 0.5494773983955383},
  {'label': 'sadness', 'score': 0.11169008165597916},
  {'label': 'disgust', 'score': 0.10400654375553131},
  {'label': 'surprise', 'score': 0.0787653997540474},
  {'label': 'anger', 'score': 0.06413350999355316},
  {'label': 'fear', 'score': 0.05136271193623543},
  {'label': 'joy', 'score': 0.04056432843208313}]]

In [14]:
sorted(predictions[0], key=lambda x: x["label"])

[{'label': 'anger', 'score': 0.00915634073317051},
 {'label': 'disgust', 'score': 0.0026284719351679087},
 {'label': 'fear', 'score': 0.06816215068101883},
 {'label': 'joy', 'score': 0.047942452132701874},
 {'label': 'neutral', 'score': 0.14038559794425964},
 {'label': 'sadness', 'score': 0.0021221598144620657},
 {'label': 'surprise', 'score': 0.7296028733253479}]

In [16]:
emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

In [17]:
def calculate_max_emotion_scores(predictions):
    per_emotion_scores = {label: [] for label in emotion_labels}
    for prediction in predictions:
        sorted_predictions = sorted(prediction, key=lambda x: x["label"])
        for index, label in enumerate(emotion_labels):
            per_emotion_scores[label].append(sorted_predictions[index]["score"])
    return {label: np.max(scores) for label, scores in per_emotion_scores.items()}

In [18]:
for i in range(10):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

In [19]:
emotion_scores

{'anger': [np.float64(0.06413350999355316),
  np.float64(0.6126185655593872),
  np.float64(0.6126185655593872),
  np.float64(0.06413350999355316),
  np.float64(0.351483553647995),
  np.float64(0.351483553647995),
  np.float64(0.08141220360994339),
  np.float64(0.08141220360994339),
  np.float64(0.23222492635250092),
  np.float64(0.23222492635250092)],
 'disgust': [np.float64(0.2735908031463623),
  np.float64(0.3482856750488281),
  np.float64(0.3482856750488281),
  np.float64(0.10400654375553131),
  np.float64(0.1507219821214676),
  np.float64(0.1507219821214676),
  np.float64(0.1844947636127472),
  np.float64(0.1844947636127472),
  np.float64(0.7271747589111328),
  np.float64(0.7271747589111328)],
 'fear': [np.float64(0.9281686544418335),
  np.float64(0.942527711391449),
  np.float64(0.942527711391449),
  np.float64(0.9723208546638489),
  np.float64(0.36070743203163147),
  np.float64(0.36070743203163147),
  np.float64(0.09504326432943344),
  np.float64(0.09504326432943344),
  np.float64(0.05136271193623543),
  np.float64(0.05136271193623543)],
 'joy': [np.float64(0.9327977299690247),
  np.float64(0.70442134141922),
  np.float64(0.70442134141922),
  np.float64(0.7672376036643982),
  np.float64(0.2518808841705322),
  np.float64(0.2518808841705322),
  np.float64(0.04056432843208313),
  np.float64(0.04056432843208313),
  np.float64(0.04337577894330025),
  np.float64(0.04337577894330025)],
 'sadness': [np.float64(0.6462157964706421),
  np.float64(0.8879395127296448),
  np.float64(0.8879395127296448),
  np.float64(0.5494773983955383),
  np.float64(0.7326866388320923),
  np.float64(0.7326866388320923),
  np.float64(0.884389340877533),
  np.float64(0.884389340877533),
  np.float64(0.6213936805725098),
  np.float64(0.6213936805725098)],
 'surprise': [np.float64(0.9671574234962463),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916),
  np.float64(0.47588080167770386),
  np.float64(0.47588080167770386),
  np.float64(0.11169008165597916),
  np.float64(0.11169008165597916)],
 'neutral': [np.float64(0.7296028733253479),
  np.float64(0.2525450885295868),
  np.float64(0.2525450885295868),
  np.float64(0.0787653997540474),
  np.float64(0.0787653997540474),
  np.float64(0.0787653997540474),
  np.float64(0.0787653997540474),
  np.float64(0.0787653997540474),
  np.float64(0.2719018757343292),
  np.float64(0.2719018757343292)]}

In [21]:
emotion_labels = ["anger", "disgust", "fear", "joy", "sadness", "surprise", "neutral"]
isbn = []
emotion_scores = {label: [] for label in emotion_labels}

for i in tqdm(range(len(books))):
    isbn.append(books["isbn13"][i])
    sentences = books["description"][i].split(".")
    predictions = classifier(sentences)
    max_scores = calculate_max_emotion_scores(predictions)
    for label in emotion_labels:
        emotion_scores[label].append(max_scores[label])

100%|██████████| 5312/5312 [06:29<00:00, 13.65it/s]

In [22]:
emotions_df = pd.DataFrame(emotion_scores)
emotions_df["isbn13"] = isbn

In [23]:
emotions_df

,anger,disgust,fear,joy,sadness,surprise,neutral,isbn13
0,0.064134,0.273591,0.928169,0.932798,0.646216,0.967157,0.729603,9780002005883
1,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545,9780002261982
2,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545,9780002261982
3,0.064134,0.104007,0.972321,0.767238,0.549477,0.111690,0.078765,9780006178736
4,0.351484,0.150722,0.360707,0.251881,0.732687,0.111690,0.078765,9780006280897
...,...,...,...,...,...,...,...,...
5307,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656,9788172235222
5308,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227764,9788173031014
5309,0.009997,0.009929,0.339216,0.947779,0.375756,0.066685,0.057625,9788179921623
5310,0.064134,0.104007,0.459269,0.759455,0.951104,0.368110,0.078765,9788185300535
5311,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765,9789027712059

In [24]:
books = pd.merge(books, emotions_df, on = "isbn13")
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,...,title_and_subtitle,tagged_description,simple_categories,anger,disgust,fear,joy,sadness,surprise,neutral
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,...,Gilead,9780002005883 A NOVEL THAT READERS and critics...,Fiction,0.064134,0.273591,0.928169,0.932798,0.646216,0.967157,0.729603
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545
2,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545
3,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545
4,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,...,Spider's Web: A Novel,9780002261982 A new 'Christie for Christmas' -...,Fiction,0.612619,0.348286,0.942528,0.704421,0.887940,0.111690,0.252545
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5537,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,...,Mistaken Identity,9788172235222 On A Train Journey Home To North...,Fiction,0.148208,0.030643,0.919165,0.255170,0.853722,0.980877,0.030656
5538,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,...,Journey to the East,9788173031014 This book tells the tale of a ma...,Nonfiction,0.064134,0.114383,0.051363,0.400263,0.883198,0.111690,0.227764
5539,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,...,The Monk Who Sold His Ferrari: A Fable About F...,9788179921623 Wisdom to Create a Life of Passi...,Fiction,0.009997,0.009929,0.339216,0.947779,0.375756,0.066685,0.057625
5540,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,...,I Am that: Talks with Sri Nisargadatta Maharaj,9788185300535 This collection of the timeless ...,Nonfiction,0.064134,0.104007,0.459269,0.759455,0.951104,0.368110,0.078765
5541,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,...,The Berlin Phenomenology,9789027712059 Since the three volume edition o...,Nonfiction,0.064134,0.104007,0.051363,0.958549,0.915193,0.111690,0.078765

In [25]:
books.to_csv("books_with_emotions.csv", index = False)